### ISSUE TITLE
[onboarding] tariff plan

### ISSUE THREAD

**Issue by Kravalg** [VilnaCRM-Org/core-service#1]
As a user, I want to be able to choose a tariff plan.

New user onboarding page.
At the top of the page should be breadcrumbs for setting up a new project, consisting of steps that you can switch between
Steps - Tariff plan, Payment, Import from CRM, Project, Product, Kanban docker, Integration, IP telephony, Employees.
The tariff plan selection page consists of two blocks, where the user can choose which plan suits him:

Free rate

Cloud solutions
No functional limitations
Up to 50 users

Price: free

Corporate rate

Cloud and box solutions
No functional limitations
No exchanges for the number of users

Price: $10 per user

[Design](https://www.figma.com/file/hubQLvQkAlz8wWs2C60T3p/VilnaCRM?type=design&node-id=0-1&t=KiZ8Iq6wInNqRgPb-0)

[User flow](https://miro.com/app/board/uXjVPQ3J5kI=/)

[Architecture](https://miro.com/app/board/uXjVPRE64mI=/)

### Technical requirements

- [ ] PHP 8
- [ ] API platform 3
- [ ] MongoDB
- [ ] AWS S3
- [ ] AWS ElastiCache
- [ ] Symfony Messenger
- [ ] Symfony Mailer
- [ ] MongoDB ODM

### Tasks

- [ ] Design architecture for C4 model
- [ ] Add MongoDB to the docker
- [ ] Implement REST API and GraphQL endpoints for user onboarding steps CRUD
- [ ] Implement REST API and GraphQL endpoints for onboarding tariff plans CRUD
- [ ] Add DB migration with default data for user onboarding steps and tariff plans
- [ ] Add [logger](https://symfony.com/doc/current/logging.html) (storage: docker stdout)
- [ ] Add documentation for REST API, GraphQL
- [ ] Research how automatically cover by e2e tests our simple endpoints
- [ ] Cover code by autotests (E2E, BDD, Behat, [OpenAPI tests generator](https://github.com/meqaio/swagger_meqa), [GraphQL tests generator](https://github.com/socialtables/graphql-test-generator))

### Acceptance criteria

- [ ] Admin panel user can handle user onboarding steps (CRUD)
- [ ] Admin panel user can handle onboarding tariff plans (CRUD)
- [ ] CRUD for user onboarding steps through REST API, GraphQL works
- [ ] CRUD for onboarding tariff plans REST API, GraphQL works
- [ ] All tests passed

**Comment by dmytrocraft** [comment]
Implemented backend onboarding endpoint names in PR #197.

REST endpoints:

- `GET /api/onboarding_steps`
- `POST /api/onboarding_steps`
- `GET /api/onboarding_steps/{ulid}`
- `PUT /api/onboarding_steps/{ulid}`
- `PATCH /api/onboarding_steps/{ulid}`
- `DELETE /api/onboarding_steps/{ulid}`
- `GET /api/tariff_plans`
- `POST /api/tariff_plans`
- `GET /api/tariff_plans/{ulid}`
- `PUT /api/tariff_plans/{ulid}`
- `PATCH /api/tariff_plans/{ulid}`
- `DELETE /api/tariff_plans/{ulid}`

GraphQL queries:

- `onboardingStep(id: ID!)`
- `onboardingSteps(...)`
- `tariffPlan(id: ID!)`
- `tariffPlans(...)`

GraphQL mutations:

- `createOnboardingStep(input: createOnboardingStepInput!)`
- `updateOnboardingStep(input: updateOnboardingStepInput!)`
- `deleteOnboardingStep(input: deleteOnboardingStepInput!)`
- `createTariffPlan(input: createTariffPlanInput!)`
- `updateTariffPlan(input: updateTariffPlanInput!)`
- `deleteTariffPlan(input: deleteTariffPlanInput!)`

Default data seed command:

- `bin/console app:onboarding:seed-defaults`
